name: CI

on:
  push: 
    branches: 
      - main

jobs: 
  build-and-push: 
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v4

      steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x' 
      
      - name: Run test
        run: go test

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker image
      run: docker build -t denisoliveirab/api-journey.api:${{ steps.generate_sha.outputs.sha}} .

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          denisoliveirab/api-journey.api:${{ steps.generate_sha.outputs.sha}}
          denisoliveirab/api-journey.api:latest

    # - name: Push image
    #   run: |
    #    docker push denisoliveirab/api-journey.api:${{ steps.generate_sha.outputs.sha}} 
    #    docker tag denisoliveirab/api-journey.api:${{ steps.generate_sha.outputs.sha}} denisoliveirab/api-journey.api:latest
    #    docker push denisoliveirab/api-journey.api:latest
    